### ISSUE TITLE
Remove debug logging

### ISSUE THREAD

**Issue by paulrutter** [anodynos/require-clean#1]
The "clean" method does a console.log() in the clean method.
Can this call be removed? It clogs my development log :)

Thanks.

**Comment by anodynos** [comment]
Yeap, will do - thanks for the issue!

**Comment by anodynos** [comment]
Solved in 0.1.3 - thanks for the report / PR, sorry for delay!

**Comment by anodynos** [comment]
@paulrutter no star :-(
